---
- name: install all apt packages
  apt: 
    name: "{{ item }}"
    state: present
    allow_unauthenticated: yes
  with_items:
   - bridge-utils
   - vlan 
   - ifenslave 
   - ifenslave-2.6    
   - tcpdump
- name: Loading the 8021.q and bonding modules
  modprobe: 
    name: "{{ item }}"
    state: present
  with_items:
    - 8021q
    - bonding
- name: Also adding 8021.q and bonding modules /etc/modules
  command: "{{ item }}"
  with_items:
   - echo '8021q' >> /etc/modules
   - echo 'bonding' >> /etc/modules
- name: Configure the network interfaces and bridges
  template:      
       src: base-hw-network.cfg.j2
       dest: /etc/network/interfaces
       backup: yes
- name: Rebooting  the server  ----watch out you may disconnected if configuration is not proper
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  #become: yes
  #become_method: sudo
  ignore_errors: true
- name: waiting for server to come back after reboot
  local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=120 timeout=300 connect_timeout=15
  retries: 50

    