---
- hosts: compute4
  vars_files: 
    - base-hardware-prep-defination.yml    
  become: true
  tasks:
  - debug:
      var: ansible_hostname
      verbosity: 2
  - name: testing network intreface template
    template:
      src: base-hw-net-interface.cfg.j2
      dest: /tmp/base-hw-net-interface.cfg
