---
- hosts: compute4
  vars_files: 
    - base-hardware-prep-defination.yml    
  become: true
  tasks:   
  - debug:
      var: network_interfaces.compute6
      verbosity: 2
  - name: testing network intreface template
    template:      
       src: test.cfg.j2
       dest: /tmp/test.cfg
