- include: os-gnocchi-install.yml
  when:
    - gnocchi_storage_driver is defined
    - gnocchi_storage_driver == 'swift'
  vars:
    gnocchi_identity_only: True
- include: os-swift-install.yml
- include: os-gnocchi-install.yml
- include: os-ironic-install.yml
- include: os-magnum-install.yml
- include: os-trove-install.yml
- include: os-sahara-install.yml
- include: os-tempest-install.yml
  when: (tempest_install | default(False)) | bool or (tempest_run | default(False)) | bool
